import type { Metadata } from 'next';
import { Gothic_A1 } from 'next/font/google';
import './globals.css';
import { cn } from '@/src/lib/utils';

const gothicA1 = Gothic_A1({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-gothic-a1',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn('min-h-screen bg-background font-sans antialiased', gothicA1.variable)}>
        {children}
      </body>
    </html>
  );
}
